# configure auto-configured MultipartConfigElement

# SPRING BOOT 1.3
#multipart.maxFileSize=50MB
#multipart.maxRequestSize=50MB
#multipart.location=${java.io.tmpdir}

# SPRING BOOT 1.5
spring
  http
    multipart
      max-file-size: 50MB
      max-request-size: 50MB
      location: ${java.io.tmpdir}

# can exclude using properties file
#spring.autoconfigure.exclude=com.fererlab.controller.UploadController

# AUTO-CONFIGURATION-CLASSES
# http://docs.spring.io/spring-boot/docs/current/reference/html/auto-configuration-classes.html
# COMMON-APPLICATION-PROPERTIES
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# DAO (PersistenceExceptionTranslationAutoConfiguration)
#spring.dao.exceptiontranslation.enabled=false
# Spring MVC
spring
  mvc
    favicon
      enabled: false

# matchers for ConditionalOnX and gif location
com
  fererlab
    create-result-dir: true
    optimize: true
    gif-location: ${java.io.tmpdir}/gif

logging:
  level.: DEBUG

